# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push tags but only for the master branch
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        YANDEX_AUTH_TOKEN: ${{ secrets.YANDEX_AUTH_TOKEN }}
        YANDEX_ORG_ID: ${{ secrets.YANDEX_ORG_ID }}
        GITHUB_SERVER_URL: ${{ github.GITHUB_SERVER_URL }}
        GITHUB_REPOSITORY: ${{ github.GITHUB_REPOSITORY }}
        GITHUB_RUN_ID: ${{ github.GITHUB_RUN_ID }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
        with:
            ref: 'master'
            fetch-depth: 0

      - name: Checkout to tag
        run: git checkout ${{ github.ref }}

      - name: Setup 14.x
        uses: actions/setup-node@v1
        with:
            node-version: 14.x

      # Save latest release tag
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
            echo $RELEASE_VERSION

      # Write commits
      - name: Run script of release
        run: |
            bash ./scripts/release.sh

      # Build
      - name: Build and update task
        run: |
            bash ./scripts/build.sh

